apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sgame-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"

spec:
  rules:
    - host: sgame.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sgame-backend-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sgame-frontend-service
                port:
                  number: 80
