apiVersion: v1
kind: Secret
metadata:
  name: sgame-secrets
stringData:
  mongo-port: "27017"
  mongo-root-user: root-user
  mongo-root-password: root-password
  mongo-name: sgame
  mongo-conn-str: mongodb://user:$password@sgame-mongo-service:port/sgame?authSource=admin
  redis-port: "6379"
  redis-user: user
  redis-password: password
  redis-db: "0"
  redis-args: "--user user allcommands allkeys allchannels on >password"
