apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgame-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgame-mongo
  template:
    metadata:
      labels:
        app: sgame-mongo
    spec:
      containers:
        - name: mongo
          image: mongodb/mongodb-community-server:6.0-ubi8
          ports:
            - containerPort: 27017
          stdin: true
          tty: true
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sgame-secrets
                  key: mongo-root-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sgame-secrets
                  key: mongo-root-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: sgame-secrets
                  key: mongo-name
          volumeMounts:
            - name: sgame-mongo-data
              mountPath: /data/db
      volumes:
        - name: sgame-mongo-data
          persistentVolumeClaim:
            claimName: sgame-mongo-pvc
